name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Dependency - MSBuild
      uses: microsoft/setup-msbuild@v1.0.1
      with:
        vswhere-path: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer' 
    - name: Versions
      run: | 
        MSBuild.exe -version