name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: dir
      run: dir
    - name: powershell
      run: Get-ChildItem -Recurse .
    - name: Versions
      run: | 
        python --version